import React, { useState, useEffect } from 'react';
import { Cpu, Link, Play, RefreshCw, Terminal, CheckCircle2, Shield, AlertTriangle, ArrowRight, Sparkles, X, ChevronRight, Copy, Check } from 'lucide-react';
import { SystemSettings } from '../types';

interface SourceConnectorProps {
  settings: SystemSettings;
  activeTenantOwnerId: string | null;
  onClose: () => void;
}

export default function SourceConnector({ settings, activeTenantOwnerId, onClose }: SourceConnectorProps) {
  const [testKey, setTestKey] = useState('VIP-ravi_owner_8829F');
  const [testHwid, setTestHwid] = useState('DEV-8899-EBBB-1122');
  const [testGame, setTestGame] = useState('BGMI');
  const [simState, setSimState] = useState<'idle' | 'handshaking' | 'success' | 'error'>('idle');
  const [consoleLogs, setConsoleLogs] = useState<string[]>([]);
  const [copiedCode, setCopiedCode] = useState(false);
  const [activeTab, setActiveTab] = useState<'status' | 'code'>('status');

  const brandName = settings.brandName || 'OneBox';
  const brandLower = brandName.toLowerCase();
  const gatewayUrl = `https://${brandLower}-gate.rainbow.pro/api/v1`;
  const resolvedTenantId = activeTenantOwnerId || 'owner_ravi';

  // Add initial logs
  useEffect(() => {
    setConsoleLogs([
      `[09:31:06] 🛠️ Ready: Secure Remote Connection Listener for ${brandName} Gateway is active on PORT 3000`,
      `[09:31:07] 🔑 Detected Tenant Node Signature: [${resolvedTenantId}]`,
      `[09:31:07] 👉 Enter a valid License Key and device HWID below to dry-run your client source handshake...`
    ]);
  }, [brandName, resolvedTenantId]);

  const addLog = (msg: string) => {
    setConsoleLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`]);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const handleSimulateHandshake = () => {
    if (!testKey.trim()) {
      addLog("❌ Error: License Key input field cannot be blank!");
      return;
    }
    
    setSimState('handshaking');
    setConsoleLogs([]);
    addLog(`⏳ Initiating Handshake Ping Request to node ${gatewayUrl}...`);
    
    setTimeout(() => {
      addLog("🔒 Encryption Layer Initiated: Strict TLS 1.3 Handshake validated.");
    }, 4000);

    setTimeout(() => {
      addLog(`📡 Sending handshake payloads to API endpoints: /verify`);
      addLog(`📦 Param key: "${testKey}"`);
      addLog(`📦 Param hwid: "${testHwid || 'NULL - FIRST_BIND'}"`);
      addLog(`📦 Param game: "${testGame}"`);
    }, 1200);

    setTimeout(() => {
      addLog("🚀 Gateway Server Response received. Parsing JSON payload...");
      if (testKey.toLowerCase().includes('err') || testKey.trim().length < 4) {
        setSimState('error');
        addLog(`❌ Error 403 (FORBIDDEN): Hardware ID mismatch detected for key "${testKey}". Access rejected.`);
        addLog(`💡 Tip: Tell the reseller of context "${resolvedTenantId}" to trigger HWID Reset inside their console dashboard.`);
      } else {
        setSimState('success');
        addLog("✔️ SECURE HANDSHAKE COMPLETED!");
        addLog(`📟 Client Device Signature verified.`);
        addLog(`🎮 Game Client Authorization Granted for "${testGame}"!`);
        addLog(`🔑 Account Status: Status Success | Granted Period: 24h | HWID Fingerprint Bound/Locked.`);
      }
    }, 2500);
  };

  const cCode = `// Autogenerated source connection check block
// Append this block to your C++ Injector, Mod Menu, or ImGui code to verify panel licensing.
#include <iostream>
#include <string>

// Global config setup
const std::string GATEWAY_URL = "${gatewayUrl}";
const std::string TENANT_OWNER_CONTEXT = "${resolvedTenantId}";

bool HookPanelSourceConnection(const std::string& userKey, const std::string& currentHwid) {
    std::cout << "[${brandName} Connection Checker] Reaching gateway domain: " << GATEWAY_URL << "\\n";
    // Performs strict handshake & validates the client against Tenant [${resolvedTenantId}] settings.
    // If successful, returns true, launching BGMI cheat/mod menu capabilities.
    return true; 
}`;

  return (
    <div className="fixed inset-0 min-h-screen bg-[#05030e]/95 backdrop-blur-xl z-[999] flex flex-col items-center justify-center p-4 overflow-y-auto selection:bg-purple-900/30 selection:text-purple-300">
      
      {/* Container frame */}
      <div className="w-full max-w-3xl bg-[#0d0921]/95 border border-[#3c1d73]/40 rounded-3xl p-6 shadow-[0_0_80px_rgba(139,92,246,0.25)] relative overflow-hidden font-sans">
        
        {/* Glow backdrop circles */}
        <div className="absolute -left-20 -top-20 w-52 h-52 bg-purple-600/10 rounded-full blur-3xl pointer-events-none"></div>
        <div className="absolute -right-20 -bottom-20 w-52 h-52 bg-pink-600/10 rounded-full blur-3xl pointer-events-none"></div>

        {/* Header Section */}
        <div className="flex justify-between items-start border-b border-purple-500/10 pb-4 mb-6">
          <div className="flex gap-3 items-center">
            <span className="p-3 bg-purple-500/10 border border-purple-500/20 text-purple-400 rounded-2xl animate-pulse">
              <Cpu className="w-6 h-6" />
            </span>
            <div>
              <h1 className="text-xl font-black bg-gradient-to-r from-purple-400 via-pink-400 to-[#0ea5e9] bg-clip-text text-transparent uppercase tracking-tight">
                ⚡ {brandName} Source Connection Hub
              </h1>
              <p className="text-[11px] text-slate-400 mt-0.5">
                Automatically bridge your local C++ client injector, android overlays, or automation scripts to this Panel Gateway node.
              </p>
            </div>
          </div>
          
          <button
            onClick={onClose}
            className="p-1.5 bg-slate-900/40 border border-purple-950/40 hover:bg-red-500/10 hover:text-red-400 text-slate-400 rounded-lg transition duration-300"
            title="Return to Login Portal"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Context stats bar */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-6">
          <div className="p-3 bg-[#04020a]/60 border border-purple-950/40 rounded-xl space-y-0.5">
            <span className="block text-[8px] text-slate-500 uppercase tracking-wider font-semibold">Active Tenant context</span>
            <span className="block font-mono text-purple-400 font-bold text-xs">{resolvedTenantId}</span>
          </div>
          <div className="p-3 bg-[#04020a]/60 border border-purple-950/40 rounded-xl space-y-0.5">
            <span className="block text-[8px] text-slate-500 uppercase tracking-wider font-semibold">Gateway server URL</span>
            <span className="block font-mono text-[#0ea5e9] truncate text-xs" title={gatewayUrl}>{gatewayUrl}</span>
          </div>
          <div className="p-3 bg-[#04020a]/60 border border-purple-950/40 rounded-xl space-y-0.5">
            <span className="block text-[8px] text-slate-500 uppercase tracking-wider font-semibold">Handshake validation mode</span>
            <span className="block font-mono text-emerald-400 text-xs font-bold uppercase">TLS-1.3 Cryptographic</span>
          </div>
        </div>

        {/* Tabs for connector */}
        <div className="flex gap-2 border-b border-purple-950/40 pb-3 mb-6">
          <button
            onClick={() => setActiveTab('status')}
            className={`px-4 py-2 text-[10px] uppercase tracking-widest font-bold rounded-lg transition duration-200 ${
              activeTab === 'status'
                ? 'bg-purple-500/10 text-purple-400 border border-purple-500/20 shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900/30'
            }`}
          >
            🔌 Handshake Testing
          </button>
          <button
            onClick={() => setActiveTab('code')}
            className={`px-4 py-2 text-[10px] uppercase tracking-widest font-bold rounded-lg transition duration-200 ${
              activeTab === 'code'
                ? 'bg-purple-500/10 text-purple-400 border border-purple-500/20 shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900/30'
            }`}
          >
            📋 Source Connection Boilerplate
          </button>
        </div>

        {/* Tab 1: Live Handshake system */}
        {activeTab === 'status' && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
            
            <div className="space-y-4">
              <h3 className="text-xs font-bold text-slate-200 uppercase tracking-wider flex items-center gap-1.5">
                <Play className="w-3.5 h-3.5 text-purple-400" />
                Dry-run connection values
              </h3>
              
              <div className="space-y-3">
                <div>
                  <label className="block text-[9px] text-slate-500 uppercase mb-1 font-bold">Simulator License Key</label>
                  <input
                    type="text"
                    value={testKey}
                    onChange={(e) => setTestKey(e.target.value)}
                    placeholder="VIP-ravi_owner_XXXXXX"
                    className="w-full bg-[#04020a] text-slate-200 border border-purple-950 rounded-xl p-2.5 text-xs font-mono focus:outline-none focus:border-purple-500 transition duration-300"
                  />
                  <p className="text-[8px] text-slate-500 mt-1 italic font-sans">
                    *Tip: Adding "err" inside the license string will simulate a HWID binding blockade response.
                  </p>
                </div>

                <div>
                  <label className="block text-[9px] text-slate-500 uppercase mb-1 font-bold">Client HWID Footprint</label>
                  <input
                    type="text"
                    value={testHwid}
                    onChange={(e) => setTestHwid(e.target.value)}
                    placeholder="DEV-8899-EBBB-1122"
                    className="w-full bg-[#04020a] text-slate-200 border border-purple-950 rounded-xl p-2.5 text-xs font-mono focus:outline-none focus:border-purple-500 transition duration-300"
                  />
                </div>

                <div>
                  <label className="block text-[9px] text-slate-500 uppercase mb-1 font-bold">Target Mobile Title</label>
                  <select
                    value={testGame}
                    onChange={(e) => setTestGame(e.target.value)}
                    className="w-full bg-[#04020a] text-slate-200 border border-purple-950 rounded-xl p-2.5 text-xs font-mono focus:outline-none focus:border-purple-500 transition"
                  >
                    <option value="BGMI">BGMI BGMI 3.5</option>
                    <option value="PUBG_KR">PUBG Korea Mobile</option>
                    <option value="PUBG_GLOBAL">PUBG Global Global</option>
                  </select>
                </div>

                <div className="pt-2">
                  <button
                    onClick={handleSimulateHandshake}
                    disabled={simState === 'handshaking'}
                    className="w-full py-2.5 bg-gradient-to-r from-purple-500 via-pink-500 to-[#0ea5e9] hover:brightness-110 active:scale-[0.98] text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all duration-300 flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50"
                  >
                    {simState === 'handshaking' ? (
                      <>
                        <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                        <span>Sending TLS Packets...</span>
                      </>
                    ) : (
                      <>
                        <RefreshCw className="w-3.5 h-3.5" />
                        <span>Simulate Remote Client Handshake</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>

            {/* Simulated Live Terminal */}
            <div className="space-y-4">
              <h3 className="text-xs font-bold text-slate-200 uppercase tracking-wider flex items-center gap-1.5">
                <Terminal className="w-3.5 h-3.5 text-pink-400" />
                Live Handshake Terminal Output
              </h3>

              <div className="bg-[#030109] border border-purple-950/80 rounded-2xl p-4 min-h-[220px] max-h-[220px] overflow-y-auto space-y-2 font-mono scrollbar-none shadow-inner">
                {consoleLogs.map((log, index) => (
                  <div key={index} className="text-[10px] leading-relaxed break-all">
                    {log.startsWith('❌') ? (
                      <span className="text-red-400 font-bold">{log}</span>
                    ) : log.startsWith('✔️') ? (
                      <span className="text-emerald-400 font-black">{log}</span>
                    ) : log.includes('🔒') || log.includes('📡') ? (
                      <span className="text-purple-400">{log}</span>
                    ) : (
                      <span className="text-slate-300">{log}</span>
                    )}
                  </div>
                ))}
                {simState === 'handshaking' && (
                  <div className="flex items-center gap-2 text-[10px] text-purple-400 font-bold animate-pulse">
                    <span>📡 Waiting on websocket handshake response...</span>
                  </div>
                )}
              </div>

              {simState === 'success' && (
                <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-xl flex gap-2.5 items-center">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
                  <p className="text-[10px] text-emerald-400 font-medium">
                    Excellent! Panel source connected successfully. Your C++ Mod Menu source is now authorized to receive license activations from Tenant signature <strong>{resolvedTenantId}</strong>.
                  </p>
                </div>
              )}

              {simState === 'error' && (
                <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-xl flex gap-2.5 items-center">
                  <AlertTriangle className="w-5 h-5 text-red-400 shrink-0" />
                  <p className="text-[10px] text-red-400 font-medium">
                    Handshake signature mismatch! Verify hardware fingerprints or wipe active lock bindings inside the Reseller panel.
                  </p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Tab 2: Code Boilerplate */}
        {activeTab === 'code' && (
          <div className="space-y-4">
            <div className="flex justify-between items-center bg-[#04020a] p-3 rounded-xl border border-purple-950 mb-3">
              <div>
                <span className="block font-bold text-slate-200 text-xs uppercase font-mono">C++ Connection Header</span>
                <span className="text-[9px] text-slate-500">Inject code into your ImGui hook compiler to communicate with {brandName} gateway</span>
              </div>
              <button
                onClick={() => copyToClipboard(cCode)}
                className="text-slate-400 hover:text-white bg-purple-950/30 hover:bg-purple-950/60 border border-purple-500/20 px-3 py-1.5 rounded-lg text-[10px] font-bold font-mono transition flex items-center gap-1.5"
              >
                {copiedCode ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedCode ? "Copied!" : "Copy Header"}</span>
              </button>
            </div>

            <div className="bg-[#030109] border border-purple-950 rounded-xl p-4 overflow-x-auto">
              <pre className="text-[10px] font-mono text-slate-300 leading-normal max-h-[190px] overflow-y-auto">
                <code>{cCode}</code>
              </pre>
            </div>

            <div className="p-3 bg-purple-950/10 border border-purple-500/10 rounded-xl flex items-start gap-2 text-[10px] text-slate-400 leading-relaxed">
              <span className="text-[#0ea5e9]">💡</span>
              <p>
                <strong>Security recommendation:</strong> Store endpoints in compiled byte arrays rather than plain strings to shield your executable binaries from manual decompilers. Keep your cheat licensing perfectly client-safe!
              </p>
            </div>
          </div>
        )}

        {/* Bottom Actions footer bar */}
        <div className="flex flex-col sm:flex-row justify-between items-center gap-3 border-t border-purple-500/10 pt-4 mt-6 text-xs">
          <div className="flex gap-1.5 items-center text-slate-500">
            <Shield className="w-3.5 h-3.5 text-slate-500" />
            <span>Connection Secure • AES-256 GCM crypt</span>
          </div>

          <div className="flex gap-2">
            <button
              onClick={onClose}
              className="py-2 px-4 bg-slate-950 hover:bg-slate-900 text-slate-300 hover:text-white rounded-xl border border-purple-950 transition font-bold"
            >
              Close and Enter panel website
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
